require 'rake/testtask'
require 'rake/clean'

Rake::TestTask.new do |t|
  t.verbose = true
  t.test_files = FileList['test/*.rb']
end

task :default do
  puts 'The following rake tasks are available:'
  puts
  puts `rake -T`.gsub /^/, '  '
end

SRC = FileList '**/*'
