name: Pegex
description: Acmeist PEG Parsing Framework
version: 0.0.3
licenses:
- type: MIT
  url: https://raw.github.com/ingydotnet/pegex-cd/master/LICENSE
copyright: 2010-2012

author:
  name: Ingy döt Net
  email: ingy@ingy.net
  url: http://ingy.net

keywords: [pegex, parsing, language, acmeism]

homepage: http://pegex.org
repository:
  url: git://github.com/ingydotnet/pegex-cd.git
  type: git
bugs:
  url: https://github.com/ingydotnet/pegex-cd/issues

npm:
  name: pegex
  main: ./lib/Pegex
  directories:
    lib: ./lib
  engines:
    node: '>=0.4.0'
  devDependencies:
    coffee-script: '>=1.3.3'
    js-yaml: '>=1.0.2'
  scripts:
    test: coffee -e '(require "./test/lib/Test/Harness").run()' test
