// Generated by CoffeeScript 1.3.3
(function() {
  var Indent, Parser,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Parser = require('../../Pegex/Parser').Parser;

  exports.Indent = Indent = (function(_super) {

    __extends(Indent, _super);

    function Indent() {
      return Indent.__super__.constructor.apply(this, arguments);
    }

    return Indent;

  })(Parser);

}).call(this);
