// Generated by CoffeeScript 1.3.3
(function() {
  var Input;

  Input = (function() {

    function Input(a) {
      if (a == null) {
        a = {};
      }
      this.string = a.string;
      this.file = a.file;
      this.handle = a.handle;
      this._buffer = '';
      this._is_eof = false;
      this._is_open = false;
      this._is_close = false;
    }

    Input.prototype.read = function() {
      var buffer;
      if (!this._is_open) {
        throw "Attempted Pegex.Input.read before open";
      }
      if (this._is_eof) {
        throw "Attempted Pegex.Input.read after EOF";
      }
      buffer = this._buffer;
      this._buffer = null;
      this._is_eof = true;
      return buffer;
    };

    Input.prototype.open = function() {
      if (this._is_open || this._is_close) {
        throw "Attempted to reopen Pegex.Input object";
      }
      if (this.string != null) {
        this._buffer = this.string;
      } else {
        throw "Pegex.Input.open failed. No source to open.";
      }
      this._is_open = true;
      return this;
    };

    Input.prototype.close = function() {
      if (this._is_close) {
        throw "Attempted to close an unopen Pegex.Input object";
      }
      this._is_open = false;
      this._is_close = true;
      this._buffer = null;
      return this;
    };

    return Input;

  })();

}).call(this);
