// Generated by CoffeeScript 1.3.3
(function() {
  var Input;

  Input = (function() {

    function Input() {}

    return Input;

  })();

  ({
    constructor: function() {
      this.string = null;
      this.file = null;
      this.handle = null;
      this._buffer = '';
      this._is_eof = false;
      this._is_open = false;
      return this._is_close = false;
    }
  });

}).call(this);
