// Generated by CoffeeScript 1.3.3
(function() {
  var Module;

  require('../Pegex/Grammar');

  require('../Pegex/Parser');

  exports.Module = Module = (function() {

    function Module() {}

    Module.prototype.parse = function(input) {
      var parser;
      parser = new this.parser(this.grammar(this.receiver));
      return parser.parse(input);
    };

    Module.prototype.grammar = function() {
      var class_name;
      class_name = "" + this.name + ".Grammar";
      return eval("class " + class_name + " extends Pegex.Grammar");
    };

    Module.prototype.parser = function() {
      return "TODO";
    };

    Module.prototype.receiver = function() {
      return "TODO";
    };

    return Module;

  })();

}).call(this);
