// Generated by CoffeeScript 1.3.3
(function() {
  var Input, Parser, Receiver;

  Input = require('../Pegex/Input');

  Receiver = require('../Pegex/Receiver');

  Parser = (function() {

    function Parser(grammar, receiver) {
      this.grammar = grammar;
      this.receiver = receiver;
      this.receiver || (this.receiver = new require('./Pegex/Receiver'));
      this.throw_on_error = true;
      this.wrap = this.receiver.wrap;
      this.input = '';
      this.buffer = '';
      this.error = null;
      this.position = 0;
      this.debug = false;
    }

    Parser.prototype.parse = function(input, start_rule) {};

    return Parser;

  })();

}).call(this);
