// Generated by CoffeeScript 1.3.3
(function() {
  var Receiver;

  exports.Receiver = Receiver = (function() {

    function Receiver() {
      this.parser;
      this.data;
      this.wrap = false;
    }

    return Receiver;

  })();

}).call(this);
