// Generated by CoffeeScript 1.3.3

/*
name:      Pegex
abstract:  Pegex - Acmeist Parsing Framework
author:    Ingy döt Net <ingy@ingy.net>
license:   MIT
copyright: 2011
*/


(function() {
  var Pegex;

  global.Pegex = exports.Pegex = Pegex = (function() {

    function Pegex() {}

    Pegex.prototype.VERSION = '0.0.1';

    return Pegex;

  })();

  exports.pegex = function(grammar, options) {
    var receiver, wrap, _ref, _ref1;
    require('./Pegex/Grammar');
    require('./Pegex/Receiver');
    if (options == null) {
      options = {};
    }
    wrap = (_ref = options.wrap) != null ? _ref : true;
    receiver = (_ref1 = options.receiver) != null ? _ref1 : new Pegex.Receiver(wrap);
    return new Pegex.Grammar(grammar, receiver);
  };

}).call(this);
